# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TROCSoundboard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TROCSoundboard
  pod 'Google-Mobile-Ads-SDK'

  target 'TROCSoundboard-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TROCSoundboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
